title: Ayodele Sowunmi
description: Technical Support Engineer building expertise in Linux, Infrastructure, Automation, and Platform Engineering
url: "https://ayodelesowunmi.github.io"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

author:
  name: "Ayodele Sowunmi"
  bio: "Technical Support Engineer focused on Linux, infrastructure, automation, and homelab-based learning."
  location: "Lagos, Nigeria"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AyodeleSowunmi"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:ayodele@ayodelesowunmi.com"

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
